### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by rrrix** [phonkee/vcontext#2]
Hello,

I was experimenting with your module and attempted to use the example you have in the README:

```python3
from vcontext import Context


def test_vcontext_ctor():
    context = Context({
        'status': 200,
        'message': 'OK',
        'result': [
            {
                'user': {
                    'username': 'phonkee',
                    'name': 'Peter Vrba'
                }
            }
        ]
    })
    assert context['result.0.user.username'] == 'phonkee'
    assert context['status'] == 200
```

However this raises an exception:
```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in test_vcontext_ctor
  File "/Users/user/project/venv/lib/python3.9/site-packages/vcontext/context.py", line 34, in __init__
    self.update(d)
  File "/Users/user/project/venv/lib/python3.9/site-packages/vcontext/context.py", line 523, in update
    self[key] = value
  File "/Users/user/project/venv/lib/python3.9/site-packages/vcontext/context.py", line 106, in __setitem__
    self._build_item(self._data, parts, value=self._build_value(value))
  File "/Users/user/project/venv/lib/python3.9/site-packages/vcontext/context.py", line 123, in _build_value
    value[i] = self._build_value(v)
  File "/Users/user/project/venv/lib/python3.9/site-packages/vcontext/context.py", line 118, in _build_value
    newvalue = self._build_value(tmp)
  File "/Users/user/project/venv/lib/python3.9/site-packages/vcontext/context.py", line 116, in _build_value
    for key in value.keys():
RuntimeError: dictionary keys changed during iteration
```

Seems like without this basic functionality, your module cannot be used :( I was looking forward to that. I hope you can take a look.

**OS:** MacOS Catalina
**Python:** 3.9
**vcontext:** 0.23

**Comment by DrWattsMitch** [comment]
I'm having the same issue working in Python3 - it seems to run fine in Python2, but the error is thrown in Python3.

**Comment by DrWattsMitch** [comment]
I believe I found a fix. The list is being edited while being iterated over, so replace this block of code on line 115:

```
if isinstance(value, dict):
     for key in value.keys():
          tmp = value.pop(key)
          newvalue = self._build_value(tmp)
          parsed = self._parse_item(str(key))
          self._build_item(value, parsed, newvalue)
```

with this block of code.

```
if isinstance(value, dict) and len(value.keys()) >= 1:
     key = list(value.keys())[0]
     tmp = value.pop(key)
     newvalue = self._build_value(tmp)
     parsed = self._parse_item(str(key))
     self._build_item(value, parsed, newvalue)
```
